# Numpy运用

## Numpy基础用法:   介绍Numpy的基本调用方法、数组的创建和数组的索引和切片


### 1. 数组创建


In [1]:
# 导入库
import numpy as np

In [2]:
arr1 = np.array([-9,7,4,3])

In [3]:
arr1

array([-9,  7,  4,  3])

In [4]:
arr2 = np.array([-9,7,4,3],dtype =float)# 尝试改变为int或者str

In [ ]:
print(arr2)

In [5]:
arr3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [6]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
# 使用其他函数创建数组
np.arange(0,10,1)   

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
np.linspace(1,10,10,endpoint = False)

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [19]:
np.linspace(1,10,11)

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

In [20]:
np.logspace(1,5,base=2,num=10)#创建等比数列

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [ ]:
np.zeros([4,5])

In [ ]:
np.eye(6)


In [ ]:
np.diag([3,4])#创建对角矩阵

In [ ]:
np.ones([2,3]) 

In [ ]:
arr3 + 1

### 2. 数组特征


In [ ]:
# 查看数组维度
arr3.ndim 

In [ ]:
arr3.shape

In [ ]:
arr3.size

In [ ]:
arr3.dtype

In [ ]:
np.array((-9,7,4,3))

In [ ]:
# 

### 3. 索引和切片


In [ ]:
arr = np.arange(1,10)

In [ ]:
arr

In [ ]:
arr[0]

In [ ]:
arr[3:5]

In [ ]:
arr[::-1]

In [ ]:
arr[-1]

In [ ]:
arr[-4:-2]

In [ ]:
# 修改元素
arr[5] = 12

In [ ]:
arr

* 视图上进行修改 数组切片是原始数组的视图，这意味着数据不会被复制，视图上的任何修改都会反映到源数据上

In [ ]:
arr_change = arr

In [ ]:
arr_change[1:3] = [17,19]

In [ ]:
arr_change

In [ ]:
arr

* 使用.copy解决视图操作问题

In [ ]:
# 一种解决的办法是使用.copy
arr_change = arr.copy()

In [ ]:
arr_change

In [ ]:
arr_change[1:3] = [1,2]

In [ ]:
arr

* 下面是二维数组的访问

In [ ]:
data2 = ((8.5,6,4.1,2,0.7),(1.5,3,5.4,7.3,9),(3.2,4.5,6,3,9),(11.2,13.4,15.6,17.8,19))
arr2 = np.array(data2)

In [ ]:
arr2

In [ ]:
arr2[2] #访问第三行，可以理解为行索引

In [ ]:
arr2[2,1] #访问第三行，可以理解为行索引

In [ ]:
arr2[:,2:4] #访问第三列

In [ ]:
arr2[1:3] #2行和3行

In [ ]:
arr2[1:,2:] #第2行到最后一行，第3列到最后一列

In [ ]:
arr2[2,1] #访问第三行，第二个元素,第一个是行索引，第二个是列索引

In [ ]:
arr2[2][1] #访问第三行，第二个元素,第一个是行索引，第二个是列索引

In [ ]:
# 逻辑索引
arr2[arr2>=3.5]

In [ ]:
arr2[~(arr2>=3.5)] #相当于小于3.5

In [ ]:
arr2[(arr2>=1.5)&(arr2<=3.5)]

* 花式索引 利用整数数组进行索引

In [ ]:
arr2[[3,2]]# 获取第4行和第三行的元素

In [ ]:
arr2[[3,2],[0,1]] #获取(3,0),(2,1) 位置上的元素

In [ ]:
arr2[:,[3,1]] #访问第四列和第二列

In [134]:
arr2[:,[1,2]] 

array([[ 6. ,  4.1],
       [ 3. ,  5.4],
       [ 4.5,  6. ],
       [13.4, 15.6]])

In [ ]:
arr2[:,1] #比较1和[1]的区别

In [ ]:
arr2[:,[1]]

In [ ]:
arr2[[1,-1],[0,1]] #获取(1,0),(-1,1) 位置上的元素,(第二行，第一列)和(最后一行,第二列)的元素

In [ ]:
# 获取第一行，最后一行，以及第一列，第二列和第四列的元素
arr2[np.ix_([0,-1],[0,1,3])]

In [ ]:
arr2[[0,-1]][:,[0,1,3]] # 获取第一行，最后一行，以及第一列，第二列和第四列的元素