# Numpy运用

## Numpy文件读写:   使用Numpy读写文件和存储文件，例如txt和csv 文件


### 1. Numpy随机数生成


In [ ]:
# 手动创建的数组往往可能受限制，有时候需要创建随机数，但计算机产生的都是伪随机数

In [ ]:
import numpy as np

In [ ]:
np.random.random(100) #生成0到1之间的随机数

In [ ]:
# 固定随机数种子

In [ ]:
np.random.seed(100)
np.random.random(100) #生成0到1之间的随机数

In [ ]:
np.random.rand(2,10)#生成均匀分布的随机数,指定形状,产生的均匀分布的

In [ ]:
#产生1到100之间的100个随机整数
np.random.randint(0,100,size= 100)

In [ ]:
np.random.uniform(low=0,high=10,size=100) #生成0到10范围内均为分布的随机数

In [260]:
#
np.set_printoptions(precision=2)# 控制小数位数

In [211]:
np.random.normal(1,3,size = 100) #生成正态分布随机数,均值和标准差

array([ 2.08,  0.73, -0.53, -0.52,  4.59,  3.41, -0.9 , -1.37,  1.34,
        2.31,  2.21, -4.08,  2.26,  6.21, -0.68, -0.89, -4.7 ,  5.14,
       -0.4 , -2.66,  0.32, -2.44,  1.78, -0.66, -0.36,  7.12,  1.  ,
       -2.07,  1.51, -3.21,  0.31,  3.3 ,  2.92,  1.52, -6.84, -0.19,
        5.98, -3.31,  4.31,  2.33,  5.01,  5.07, -2.46,  0.84, -1.44,
       -1.26,  0.98, -4.37, -0.62,  2.03, -4.52,  0.57,  3.11, -2.27,
        0.32, -1.18,  7.36,  2.62,  5.77,  2.54,  2.67,  1.4 , -0.92,
        1.99, -1.03,  2.59,  5.01,  1.5 , -0.97, -4.68, -1.8 , -1.4 ,
       -2.05,  6.72,  3.44,  1.18, -0.91, -0.46, -0.63,  1.09,  1.82,
        1.93, -0.93,  5.86,  4.19,  1.04,  5.82,  0.56, -4.31, -1.5 ,
        0.11,  2.27, -0.49, -2.62,  0.85,  0.32, -1.46,  2.53,  7.94,
        1.14])

In [ ]:
np.random.randn(10,2) #生成标准正态分布随机数，2维

In [ ]:
samples = np.random.normal(size=(4,4))
print(samples)
# 生成一个标准正太分布的4*4样本值

In [ ]:
s = np.array([1,2,5,7,9,10])

In [ ]:
np.random.shuffle(s)# 打乱S

In [ ]:
s

In [ ]:
np.random.permutation(s) #重新排列

### 2. Numpy统计相关函数


In [ ]:
# 读取csv文件
data = np.genfromtxt(r'E:\云开明培训机构\云开见明培训课件\Numpy运用\arr.txt',delimiter=',',skip_header= 1)

In [ ]:
data.shape

In [ ]:
data.sum()#求和

In [ ]:
data.mean() #求均值

In [ ]:
print(data.sum(axis=0)) #对列进行求和

In [ ]:
print(data.mean(axis=0)) #对列进行求均值

* 0代表纵轴，即沿着纵轴计算，就是按列计算，1代表横轴，即沿着横轴，就是按行进行计算

In [ ]:
print(data.sum(axis=1)) #对行进行求和 
print(data.mean(axis=1)) #对行进行求和均值

In [ ]:
print(data.cumsum()) #累计求和

In [ ]:
print(data.cumsum(axis=1)) #累计求和

In [ ]:
print(data.cumprod()) #累计积


In [ ]:
print(data.cumprod(axis=0))

In [ ]:
print(data.cumprod(axis=1))

In [ ]:
print(data.max()) #最大值

In [ ]:
print(data.max(axis=0))

In [ ]:
print(data.max(axis=1))

* np.percentile用于计算分位数

In [ ]:
np.percentile(data,10)

In [199]:
np.percentile(data,[0,25,50,75,100])

array([0.002688  , 0.31808625, 0.516569  , 0.74815075, 0.995358  ])

* np.ptp用于计算极差

In [ ]:
np.ptp(data)

In [ ]:
np.ptp(data,axis=0)

In [ ]:
np.ptp(data,axis=1)

In [198]:
# 大于3的元素个数总数
np.sum(data>0.3)

33

### 3. Numpy线性代数

In [215]:
# 一维数组的点积
a = np.array([1,2,3])
b = np.array([4,5,6])
vector_dot = np.dot(a, b)
print('一维数组的点积：\n',vector_dot)

一维数组的点积：
 32


In [241]:
arr5 = np.array([5,15,25,40]).reshape(4,1)
arr6 = np.arange(12).reshape(3,4)

In [242]:
arr2d = np.dot(arr6,arr5)

In [249]:
arr2d

array([[185],
       [525],
       [865]])

In [246]:
arr9 = np.array([[1,2,3],[4,5,6]])
arr10 = np.array([[6,23],[-1,7],[8,9]])
np.dot(arr9,arr10)

array([[ 28,  64],
       [ 67, 181]])

In [251]:
arr11 = np.array([[6,-1],[8,1]])
arr12 = np.array([[6,10],[-1,1]])

In [252]:
np.dot(arr11,arr12)

array([[37, 59],
       [47, 81]])

In [253]:
arr11*arr12

array([[ 36, -10],
       [ -8,   1]])

In [255]:
# 矩阵的转置
data2 = ((8.5,6,4.1,2,0.7),(1.5,3,5.4,7.3,9),(3.2,4.5,6,3,9),(11.2,13.4,15.6,17.8,19),(12,3.4,1.2,4,7))
arr2 = np.array(data2)
arr2.T

array([[ 8.5,  1.5,  3.2, 11.2, 12. ],
       [ 6. ,  3. ,  4.5, 13.4,  3.4],
       [ 4.1,  5.4,  6. , 15.6,  1.2],
       [ 2. ,  7.3,  3. , 17.8,  4. ],
       [ 0.7,  9. ,  9. , 19. ,  7. ]])

In [256]:
np.transpose(arr2)

array([[ 8.5,  1.5,  3.2, 11.2, 12. ],
       [ 6. ,  3. ,  4.5, 13.4,  3.4],
       [ 4.1,  5.4,  6. , 15.6,  1.2],
       [ 2. ,  7.3,  3. , 17.8,  4. ],
       [ 0.7,  9. ,  9. , 19. ,  7. ]])

In [257]:
#逆矩阵
from numpy.linalg import inv
arr2_inv = inv(arr2)
print(arr2_inv)

[[ 0.38  0.65 -0.05 -0.31  0.03]
 [-1.04 -2.13  0.15  0.95  0.08]
 [ 1.05  1.84 -0.03 -0.82 -0.2 ]
 [-0.06  0.   -0.21  0.09  0.01]
 [-0.3  -0.39  0.14  0.15  0.08]]


In [265]:
np.dot(arr2_inv,arr2)

array([[ 1.e+00, -2.e-15, -6.e-16, -2.e-15, -1.e-15],
       [ 2.e-15,  1.e+00,  3.e-15,  6.e-15,  4.e-15],
       [-8.e-16, -2.e-15,  1.e+00, -8.e-16, -5.e-16],
       [-6.e-17,  7.e-17, -8.e-17,  1.e+00,  7.e-17],
       [-6.e-16,  5.e-16,  6.e-17,  3.e-16,  1.e+00]])

In [272]:
np.set_printoptions(suppress=True)# 控制小数位数
np.dot(arr2_inv,arr2)


array([[ 1., -0., -0., -0., -0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [-0., -0.,  1., -0., -0.],
       [-0.,  0., -0.,  1.,  0.],
       [-0.,  0.,  0.,  0.,  1.]])

In [280]:
# 求对角元素
print('5x5的矩阵: \n',arr2)
print('取出矩阵的主对角线元素: \n', np.diag(arr2))

5x5的矩阵: 
 [[ 8.5  6.   4.1  2.   0.7]
 [ 1.5  3.   5.4  7.3  9. ]
 [ 3.2  4.5  6.   3.   9. ]
 [11.2 13.4 15.6 17.8 19. ]
 [12.   3.4  1.2  4.   7. ]]
取出矩阵的主对角线元素: 
 [ 8.5  3.   6.  17.8  7. ]


* 求解方程组

* 3x + 2y + z  = 39;
* 2x + 3y + z  = 34;
* x  + 2y + 3z = 26;

In [ ]:
# 首先创建矩阵

In [ ]:
A = np.array([[3,2,1],[2,3,1],[1,2,3]]) #3行3列

In [284]:
b = np.array([[39],[34],[26]]) # 3行一列

In [285]:
X = np.linalg.solve(A,b)
print('三元一次方程组的解：\n',X)

三元一次方程组的解：
 [[9.25]
 [4.25]
 [2.75]]


* https://www.kesci.com/home/project