# Numpy运用

## Numpy文件读写:   使用Numpy读写文件和存储文件，例如txt和csv 文件


### 1. Numpy文件读取


In [216]:
# 导入相关库
import numpy as np

In [ ]:
# 读取文件
data  = np.genfromtxt(r'E:\云开明培训机构\云开见明培训课件\Numpy运用\arr.txt',delimiter=',')

In [ ]:
data

In [ ]:
# 读取csv文件
data = np.genfromtxt(r'E:\云开明培训机构\云开见明培训课件\Numpy运用\sales.csv',delimiter=',',skip_header= 1)

In [ ]:
data

In [ ]:
# 使用loadtxt读取
data  = np.loadtxt(r'E:\云开明培训机构\云开见明培训课件\Numpy运用\arr.txt',delimiter=',')

In [ ]:
data

### 2. Numpy文件存储


savetxt(fname,data,delimiter,fmt)
* fname --保存的文件路劲
* data --数据(array格式)
* delimiter --分隔符
* fmt --存储数据的格式

In [ ]:
# 数据存放
np.savetxt(r'E:\云开明培训机构\云开见明培训课件\Numpy运用\array.txt',data, delimiter=',',fmt='%.3f' )

In [ ]:
np.savetxt(r'E:\云开明培训机构\云开见明培训课件\Numpy运用\array.csv',data, delimiter=',',fmt='%.3f' )

### 3. 字符串操作

* 字符串操作函数

In [ ]:
# 列表操作
str_list = ['hello','world']
# 字母大写

In [ ]:
str_list = [i.upper() for i in str_list]

In [ ]:
str_list

In [ ]:
# 运用numpy.char模块处理

In [ ]:
str_arr = np.char.upper(str_list)

In [ ]:
str_arr

* 尽量使用numpy函数处理，比写循环快多了

In [ ]:
np.char.add(['中国','国庆'],['海军','大阅兵'])

In [ ]:
np.char.multiply(['中国','万岁'],3)

In [ ]:
np.char.join([':','-'],['hello','world']) #字符串的拆分

In [ ]:
# 去除字符串指定符号
np.char.strip(['-电动汽车','海洋科技-','-学习python'],'-')

In [ ]:
np.char.replace(['我想学习一下Python','好好学习一下java'],'学习一下','深入学习')

* 字符串查询函数

In [ ]:
# 使用案例数据

In [ ]:
# 读取案例数据

In [190]:
f = open(r'E:\云开明培训机构\云开见明培训课件\data summary\第一章\短信.txt',encoding = 'utf-8')
f_read = f.readlines()

In [200]:
S =  f_read[3]

In [201]:
# 分割
arr = S.split('\t')

In [202]:
arr = np.char.rstrip(arr,'\n')

In [204]:
arr =  np.char.replace(arr,'"','')

In [205]:
arr 

array(['10655025160191264174',
       '【利信金融】何伟， 国内领先互联网金融企业-利信金融成都总部运营中心邀您明天下午2点面试“客户顾问岗”。稳定月薪5-8k，上不封顶，早9晚6，周末双休，5险1金，免费供应零食。地址：成都市孵化园中航国际中心A座24楼。张经理17381912297，退订回T',
       '2017-12-14 04:00:53', '1', '2017-12-20 16:41:16', '何伟',
       '17612845447', '513002199402172013', '2017-12-13 09:08:42'],
      dtype='<U128')

In [206]:
np.char.find(arr,'互联网金融')

array([-1, 14, -1, -1, -1, -1, -1, -1, -1])

In [207]:
np.char.islower(arr)

array([False, False, False, False, False, False, False, False, False])

In [209]:
np.char.isdigit(arr)


array([ True, False, False,  True, False, False,  True,  True, False])

In [210]:
np.char.isalpha(arr)

array([False, False, False, False, False,  True, False, False, False])

In [215]:
np.char.count(arr,'金融')

array([0, 3, 0, 0, 0, 0, 0, 0, 0])

In [213]:
np.char.startswith(arr,'互联网金融')

array([False, False, False, False, False, False, False, False, False])

In [214]:
np.char.endswith(arr,'互联网金融')

array([False, False, False, False, False, False, False, False, False])